services:
  trawl:
    depends_on: !override
      trawl-warp:
        condition: service_healthy
    extends:
      file: https://github.com/germondai/trawl.git#dev:docker-compose.prod.yml
      service: trawl
    pids_limit: 1024
    ports: !override
      - 127.0.0.1::8191

  trawl-warp:
    container_name: !reset null
    extends:
      file: https://github.com/cmj2002/warp-docker.git
      service: warp
    volumes:
      - trawl_warp:/var/lib/cloudflare-warp
    ports: !reset []

volumes:
  trawl_metrics:
  trawl_proxy_ca:
  trawl_warp:
