services:
  browser-connector-cluster:
    environment:
      - CAMOUFOX_GEOIP=false
      - CAMOUFOX_MODE=pool
    image: ghcr.io/oyedejioyewole/browser-connector:edge
    ports:
      - 127.0.0.1:8080:8080
    restart: unless-stopped

  browser-connector-gateway:
    depends_on:
      browser-connector-cluster:
        condition: service_healthy
    environment:
      - NITRO_APP_SECRET=${NITRO_APP_SECRET}
      - NITRO_UPSTREAM_URL=${NITRO_UPSTREAM_URL}
    image: ghcr.io/oyedejioyewole/browser-connector-gateway:latest
    ports:
      - 127.0.0.1:3000:3000
    restart: unless-stopped
    volumes:
      - browser-connector-gateway:/app/.data

volumes:
  browser-connector-gateway:
