include:
  - path: https://github.com/germondai/trawl.git

name: browser-connector

services:
  cluster:
    depends_on:
      trawl:
        condition: service_healthy
    extends:
      file: ./docker/shared/compose.yaml
      service: cluster
    ports:
      - 8080:8080
      - 9222:9222
    volumes:
      - trawl_proxy_ca:/usr/local/share/ca-certificates/trawl:ro

  gateway:
    build: .
    depends_on:
      cluster:
        condition: service_healthy
    extends:
      file: ./docker/shared/compose.yaml
      service: gateway
    ports:
      - 3000:3000
    volumes:
      - gateway-data:/app/.data

  trawl:
    depends_on:
      warp:
        condition: service_healthy
    environment:
      - RESIDENTIAL_PROXY_URL=${RESIDENTIAL_PROXY_URL:-socks5://warp:1080}
    restart: unless-stopped

  warp:
    container_name: !reset null
    extends:
      file: https://github.com/cmj2002/warp-docker.git
      service: warp
    ports: !reset []
    restart: unless-stopped
    volumes:
      - warp-cloudflare-warp:/var/lib/cloudflare-warp

volumes:
  gateway-data:
  warp-cloudflare-warp:
