name: browser-connector

services:
  cluster:
    environment:
      - CAMOUFOX_DEBUG=true
      - CAMOUFOX_GEOIP=false
      - CAMOUFOX_MODE=pool
    image: ghcr.io/oyedejioyewole/browser-connector:edge
    ports:
      - 8080:8080
    restart: unless-stopped
    # More shared memory for multiple browsers
    shm_size: 3gb

  gateway:
    build: .
    depends_on:
      cluster:
        condition: service_healthy
    environment:
      - NITRO_APP_SECRET=${NITRO_APP_SECRET:?}
      - NITRO_UPSTREAM_URL=${NITRO_UPSTREAM_URL:?}
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - browser-connector-gateway:/app/.data

volumes:
  browser-connector-gateway:
    name: browser-connector-gateway-data
